import fs from 'node:fs/promises';

const astroOrStorybook = process.argv[2];

console.log(`
---- config_util.js ----
write confit to vite.config.ts for ${astroOrStorybook}
---- config_util.js ----
`);

const astro = `// generated by config_util.js

export default {};
`;

const storybook = `// generated by config_util.js

import { getViteConfig } from 'astro/config';
export default getViteConfig({});
`;

await fs.writeFile('vite.config.ts', astroOrStorybook === 'astro' ? astro : storybook);