/*
このスクリプトのために書きかえたファイル
package.json
.gitignore
*/

import fs from 'node:fs/promises';

const astroOrStorybook = process.argv[2];

const commonConfig = {
    import: `
    import postcssNesting from "postcss-nesting";
    `,
    config: `
    css: {
        postcss: {
            plugins: [postcssNesting],
        },
    },
    `,
};

console.log(`
---- config_util.js ----
write confit to vite.config.ts for ${astroOrStorybook}
---- config_util.js ----
`);

const astro = `// generated by config_util.js

${commonConfig.import}

export default {
    ${commonConfig.config}
};
`;

const storybook = `// generated by config_util.js

${commonConfig.import}

import { getViteConfig } from 'astro/config';
export default getViteConfig({
    ${commonConfig.config}
});
`;

await fs.writeFile('vite.config.ts', astroOrStorybook === 'astro' ? astro : storybook);