import type { Meta } from '@storybook/react';
import EventCard from '.';

const meta: Meta<typeof EventCard> = {
    component: EventCard,
}

export default meta;

export const Default = {
    args: {
        children: `
Lorem ipsum dolor sit amet ea duo gubergren ea rebum et ipsum in. Clita diam et nibh takimata ullamcorper est euismod diam lorem kasd elitr et laoreet consetetur at dolor voluptua consequat. Rebum illum accumsan diam amet te augue diam sadipscing consequat consequat lorem.
Vero clita tempor eros et sed tation ipsum et amet eros lorem duo veniam et. Vero accusam ea aliquyam consequat at ut aliquyam adipiscing kasd elitr ea esse dolore duo elitr elit stet. Eu et at lorem sadipscing ipsum dolore nihil sadipscing ipsum dolor elitr ipsum elitr ipsum vel rebum iusto. Aliquip lorem quis sea aliquyam vulputate commodo duis invidunt at eos ipsum molestie sanctus. Elit lorem dolor tempor et kasd at magna vero dolore elit diam. Sanctus eirmod elitr iusto qui. Diam amet lorem illum nulla dolor duis et at justo kasd amet erat et suscipit nulla. Dolore sed luptatum nonumy. Duo facer euismod enim consectetuer suscipit lorem lorem sit. Elit sanctus erat stet nulla eos at.
Invidunt lorem clita rebum tempor hendrerit et et ipsum amet gubergren amet lorem et. Magna adipiscing est et eum ipsum. Et duo labore et et sed nonumy stet no. Labore sanctus lorem iriure takimata nonummy sit at wisi eum in.
Duo nonummy dolore dolore et amet duo. Sea vero sit at sadipscing vel nibh enim rebum accusam ut elitr volutpat eos zzril dolore. Vero lorem invidunt elitr magna eu voluptua justo gubergren sit illum laoreet feugait dolor stet sed clita kasd dolore. Duo stet aliquyam clita voluptua tempor iusto lobortis rebum sadipscing sed ea at erat at. Consequat amet dolor amet nulla tempor ut imperdiet sed elitr cum at et dolores dolore clita sit et. Consetetur vero diam. Diam takimata diam sanctus dolores eos magna dolor. Accusam dolores feugait tempor rebum tempor quis accumsan dolore dolor est.
Clita consectetuer dolor clita et congue consetetur consetetur. Et te molestie ipsum eirmod est eirmod dolores magna. Amet nonumy dolor sanctus nibh kasd dolore ipsum esse amet stet est justo. Consetetur amet consequat elitr sanctus sea accusam consequat stet in amet ipsum volutpat nulla. Elitr magna amet quis rebum in nulla no nonummy odio amet duo sit lorem dolore dolor dolores sanctus. Voluptua elitr ex aliquyam sit magna duo no sit ut gubergren nonummy sea consequat lorem aliquyam et. Diam est sit feugiat invidunt est accusam. Nonumy accusam magna diam consectetuer erat elitr dolore tempor takimata velit diam ipsum autem rebum. Amet sea volutpat erat quis sit invidunt vel elitr labore diam sit diam clita. Augue sed sed sed vel sed illum amet magna dolores tempor dolore elitr dolor qui odio stet nostrud ipsum. Erat lorem sed at lobortis labore. Sit ea velit vero labore sadipscing sit voluptua rebum sea. Dolores dolores dolore sadipscing hendrerit diam.
Duis lorem lobortis dolor dolore kasd sit ullamcorper diam feugiat duo stet ipsum nostrud placerat invidunt. Facilisis kasd dolor eirmod. Ea dignissim vel facilisi facilisi justo nonumy justo rebum ea diam et sed soluta takimata aliquyam sed. Et aliquip vero luptatum wisi consetetur et nonumy dolor amet clita rebum et labore erat est nam ipsum elit. Ex sit est sea veniam lorem eos aliquyam voluptua eirmod sed te ipsum ipsum voluptua sanctus et. Diam qui ut cum accumsan. Voluptua amet lorem diam elitr invidunt sit lobortis vulputate nonumy diam ea magna. Sit kasd accusam placerat dolores nisl dolores sit dolore duo eum vero accusam iusto augue erat lorem sit. Kasd luptatum erat est dolores velit clita elitr.
Nostrud possim sed. Duo dolor erat ipsum dolore consectetuer ipsum voluptua tincidunt sit magna vero sit amet ut sanctus. Ut tempor sanctus justo labore eos nonumy lorem. Luptatum quis mazim magna at consequat. Elit soluta at wisi dolore gubergren et et lobortis voluptua at sed at. Consequat qui sit sed et dolor ut diam nisl at nonumy. No et takimata labore hendrerit diam soluta. Nobis aliquyam consequat et diam eum sadipscing nulla ea vero sed elit erat erat amet gubergren. Iusto magna ut lobortis sea. Lorem elit et commodo no duo ut soluta amet lobortis tempor lorem est est luptatum amet aliquyam ipsum. At et zzril vero ea duis ut consequat aliquyam accusam tincidunt dolor blandit nulla magna amet te.
Autem imperdiet aliquyam vulputate et. Sed voluptua sed dolore vero tempor diam magna lorem et lorem ipsum sanctus ullamcorper est sanctus ipsum ipsum adipiscing. Accusam lorem aliquyam vero odio sanctus vero labore ipsum vero iriure dolore nonumy ipsum eos accusam labore. Facilisi et labore et eirmod at. Aliquyam suscipit wisi erat in takimata nostrud no rebum dignissim nisl dolor dolores duo sit erat justo. Odio eirmod ea stet ut amet ut accusam dolore dolor ipsum sed justo et est vel. Aliquam no illum sit consequat est zzril id tincidunt dolore vero. Lorem vero eirmod et consetetur ad erat stet sit erat ut molestie tempor vero veniam dolor invidunt sit sanctus. Lorem kasd eu ea nisl magna ut. Volutpat duo ipsum dolore kasd. Sed mazim gubergren stet in labore. Illum dolore lorem vero dolor elitr kasd. Invidunt no sed elit et eu clita. Sit adipiscing erat nonummy accusam enim et aliquyam. Nonummy labore sit duo. Eos elitr nam elitr ut consequat diam autem suscipit et vero eos. Dolor takimata amet kasd takimata dolore amet nisl.
Laoreet clita nonumy in at invidunt hendrerit at rebum at sit. Illum eos diam clita ut ad. Voluptua diam ullamcorper sed et takimata lobortis invidunt minim diam erat justo vel et dolore ut. Ea erat sit nulla dolores sed consetetur erat no nonumy placerat at vulputate erat takimata justo stet vero takimata. Ipsum sanctus ut tempor consectetuer vero eos nobis facilisi aliquip dolor nonumy nonumy at wisi nihil wisi ea gubergren. Stet invidunt lorem blandit dolores iriure at ad vero amet. Et et justo dolores gubergren consetetur ipsum eos sadipscing ut hendrerit accumsan in sed. Eirmod ea augue erat erat kasd ea praesent dolor. Duo vel invidunt sadipscing duis. Sed sanctus diam ea vulputate et elitr suscipit ex. Iriure dolores takimata est clita consetetur ut consequat ex.
Consetetur ipsum placerat. Blandit dolores est elitr sed clita veniam nulla vel congue et at kasd ea dolores vero sadipscing eros lorem. Autem id ea amet eos no erat facilisi sanctus nonummy et nonummy iriure commodo vel dolor vulputate stet no. Ea sea sanctus sanctus sed iusto. Et consectetuer tempor eros ipsum gubergren euismod accusam sea vel sanctus duo justo voluptua sea. Diam ea et doming clita rebum ipsum tempor stet ut gubergren sit et nonumy nulla. Et euismod tempor et dignissim justo rebum dolores nonumy sed dolore duo nulla clita diam nibh sea eirmod. Quis erat diam diam lorem et lorem stet dolores voluptua et dolor justo. Vel dolore dolore iusto ut consectetuer accusam sit sea at labore dolor et eos amet consetetur iusto.
        `,
        type: 'plain',
    },
};